version: "3.9"
services:
  webapp:
    build: ./webapp
    ports:
      - "8000:8000" # Not sure which ports to use yet, placeholder 
  # db:
  #   build: ./db
  #   ports:
  #     - "8000:8000" # Not sure which ports to use yet, placeholder
